/* This file is generated by Ziggy. */
declare module "ziggy-js" {
    interface RouteList {
        login: [];
        logout: [];
        "password.request": [];
        "password.reset": [
            {
                name: "token";
            },
        ];
        "password.email": [];
        "password.update": [];
        "verification.notice": [];
        "verification.verify": [
            {
                name: "id";
            },
            {
                name: "hash";
            },
        ];
        "verification.send": [];
        "user-profile-information.update": [];
        "user-password.update": [];
        "password.confirmation": [];
        "password.confirm": [];
        "two-factor.login": [];
        "two-factor.enable": [];
        "two-factor.confirm": [];
        "two-factor.disable": [];
        "two-factor.qr-code": [];
        "two-factor.secret-key": [];
        "two-factor.recovery-codes": [];
        "terms.show": [];
        "policy.show": [];
        "profile.show": [];
        "other-browser-sessions.destroy": [];
        "current-user-photo.destroy": [];
        "current-user.destroy": [];
        "sanctum.csrf-cookie": [];
        graphql: [];
        "ignition.healthCheck": [];
        "ignition.executeSolution": [];
        "ignition.updateConfig": [];
        welcome: [];
        dashboard: [];
        orders: [];
        project: [
            {
                name: "id";
            },
        ];
        "project.log": [
            {
                name: "id";
            },
        ];
        "project.summary": [
            {
                name: "id";
            },
        ];
        users: [];
    }
}
export {};
